services:
  zerowork:
    image: ghcr.io/horosin/zerowork-docker:latest
    ports:
      - "5900:5900"
    environment:
      - DISPLAY=:0
    volumes:
      - /dev/shm:/dev/shm
    restart: unless-stopped
