name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Trigger on push to main branch
  workflow_dispatch: # Allows manual triggering from GitHub Actions tab

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to GitHub Container Registry using the GitHub Actions token
      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      # Build the Docker image and push to GitHub Container Registry
      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/horosin/zerowork-docker:latest .
          docker push ghcr.io/horosin/zerowork-docker:latest

      # Optionally log out from GitHub Container Registry
      - name: Log out from GitHub Container Registry
        run: docker logout ghcr.io
